### ISSUE TITLE
Create a demo org (and package it!)

### ISSUE THREAD

**Issue by shunkosa** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#44]
## Summary
Currently, in order to try the mobile app, the admin needs to manually add custom fields and add sections to the edit page. Based on [the personas and user stories we came up with in the past Sprint](https://docs.google.com/document/d/14CQrP2y631f6i-jtEYCP3NqEuphqI5I9e_9UAccJp8U), let's create a set of custom fields and page layout so that we can demo easily. And then, @shunkosa will package the metadata of the demo org as an extension package based on our existing base package. As a result, the newcomers will be able to start to try the mobile app quickly just installing the base package and the additional package.

## Package dependencies
- Grassroots Mobile Survey App Salesforce Package (Existing package which contains base object settings.)
  - Demo Salesforce Package (This work. e.g., disaster related fields, home care related fields, and so on.)

## Tasks
- [x] List the fields (Thanks Andy)
- [x] Review the fields (by Everyone)
- [x] Create the sections/fields in a new dev/TP org after installing the existing package (#53)
- [x] [Cancelled - Tasks for Play Store/ App Store]Create some example contacts, relations, surveys records that can be shown as screenshots on app store (Anyone who can help?)
- [x] Package the fields (Shun will extract metadata using Salesforce CLI or Metecho. Example records will be pushed in the repo as json format) #54

**Comment by BRDPro** [comment]
I am not sure if you have seen the user stories we have created, @shunkosa . They are [here](https://docs.google.com/spreadsheets/d/1vAe-aENiSn-NEQrVfbG0CedRNMwPqvXNQlAzcD75pSY/edit?usp=sharing). I will work on a custom field list now.

**Comment by BRDPro** [comment]
I recorded my Field List Proposal [here](https://docs.google.com/spreadsheets/d/1U1qbfa-fL87TVlT2ssjURv9tM53fzEMJW1MG-WWSFBY/edit?usp=sharing)

**Comment by shunkosa** [comment]
Thank you so much @BRDPro! Let me open until the fields are fixed and the packaged.

**Comment by shunkosa** [comment]
@eehjunggnujhee Notice that No.3 and No.4 fields in Andy's list are already in the package.

**Comment by eehjunggnujhee** [comment]
Let me review and will get that details down for Metecho. @shunkosa

**Comment by shunkosa** [comment]
This issue is intended to package the first version of sample survey metadata. We've already achieved it.
